### PR TITLE
Center source control points before estimating transformation matrix

### PR DESCRIPTION
**Pull request by jwindhager**
This pull requests changes the behavior of estimating the transformation matrix: instead of directly estimating a projective transform from the source control point set A to the target control point set B, now the source control point set A is centered (around the control point's centroid) before estimating the transform. This might help with accuracy. 

Please let me know if/how well it works before accepting this pull request. To install napping from this pull request, run:
```bash
pip install git+https://github.com/BodenmillerGroup/napping.git@centroid-transform
```

Note that the transform file format changed and the transforms must therefore be recreated from previously saved control points.

### CODE REVIEW

**Comment by nilseling** [comment]
Hey,

I get this error when trying to transform from jpg to .czi (no post-transformation):

```
Traceback (most recent call last):
  File "/Users/nils/opt/anaconda3/envs/napping_imc/bin/napping", line 8, in <module>
    sys.exit(main())
  File "/Users/nils/opt/anaconda3/envs/napping_imc/lib/python3.9/site-packages/napping/__main__.py", line 33, in main
    if not controller.show_dialog():
  File "/Users/nils/opt/anaconda3/envs/napping_imc/lib/python3.9/site-packages/napping/napping.py", line 71, in show_dialog
    return self.load_dir(
  File "/Users/nils/opt/anaconda3/envs/napping_imc/lib/python3.9/site-packages/napping/napping.py", line 164, in load_dir
    return self._show()
  File "/Users/nils/opt/anaconda3/envs/napping_imc/lib/python3.9/site-packages/napping/napping.py", line 429, in _show
    self._update_current_transformed_coords()
  File "/Users/nils/opt/anaconda3/envs/napping_imc/lib/python3.9/site-packages/napping/napping.py", line 469, in _update_current_transformed_coords
    coords[:2] = self._current_source_coords.loc[:, ['X', 'Y']].values
ValueError: could not broadcast input array from shape (3,2) into shape (2,)
``` 

I did check that the input corrdinates contain the 'X' and 'Y' column

**Comment by jwindhager** [comment]
Apologies, that's a stupid mistake on my end that I didn't notice when testing - will fix it asap and rerequest a review

**Comment by jwindhager** [comment]
Any update here @nilseling?

**Comment by nilseling** [comment]
Yes, so the transformed coordinates have an offset of 0.1um compared to the old transformation. So no change to the old implementation. Feel free to keep the old one or use the new approach.

**Pull request merged**
