### PR TITLE
Handover (v0.2.4)

### PR DESCRIPTION
**Pull request by jwindhager**
This will be a maintenance release, following some minor bugfixes (mostly related to typing)

### CODE REVIEW

**Review by Milad4849 — APPROVED** [review]
lgtm

**Comment by jwindhager** [comment]
Huh, something went wrong here. Did we forget to merge this PR before releasing v0.2.4, @Milad4849 ?

**Comment by jwindhager** [comment]
Should we release a v0.2.5 to propagate the change (with an according note in the change log, of course)?

**Comment by jwindhager** [comment]
Ping @Milad4849

**Comment by jwindhager** [comment]
Ping @Milad4849

**Pull request merged**
